name: Run code quality checks

on:
    pull_request:
        branches: [master, develop]
    push:
        branches: [master]

jobs:
    phpcs_check:
        name: PHPCS check on PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4]

        steps:
            # Checkout repository
            - name: Checkout
              uses: actions/checkout@v2

            # Setup PHP versions, run checks
            - name: PHP setup
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                coverage: pcov

            - name: Get composer cache directory
              id: composer-cache
              run: |
                echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-composer-

            - name: Install composer packages
              run: composer install --no-progress

            - name: Check coding standards using PHPCS
              run: composer standards:check -- --runtime-set testVersion ${{ matrix.php }}-

    phpstan:
        name: PHPStan check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: PHP setup
              uses: shivammathur/setup-php@v2
              with:
                php-version: 7.2
                coverage: pcov

            - name: Install composer packages
              run: composer install --no-progress

            - name: Analyse code using phpstan
              run: composer analyze

    tests:
        name: Integration tests
        runs-on: ubuntu-latest

        services:
            mysql:
              image: mysql:5.7
              env:
                MYSQL_USER: admin
                MYSQL_PASSWORD: password
                MYSQL_DATABASE: wordpresstest
                MYSQL_ROOT_PASSWORD: password
              ports:
                - 3306
              options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Verify MySql connection
              env:
                PORT: ${{ job.services.mysql.ports[3306] }}
              run: |
                while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
                  sleep 1
                done

            - name: PHP setup
              uses: shivammathur/setup-php@v2
              with:
                php-version: 7.2
                coverage: pcov

            - name: Set Node.js version
              uses: actions/setup-node@v1
              with:
                node-version: 14

            - name: Cache node modules
              uses: actions/cache@v1
              with:
                path: node_modules
                key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.OS }}-build-${{ env.cache-name }}-
                  ${{ runner.OS }}-build-
                  ${{ runner.OS }}-

            - name: Get composer cache directory
              id: composer-cache
              run: |
                echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-composer-

            - name: Install composer packages
              run: composer install --no-progress

            - name: Install node packages
              run: npm install

            - name: Run JS build
              run: npm run build

            # Setup WordPress so that we can run tests
            - name: Set up WordPress instance so that we can run tests
              run: |
                sudo systemctl start mysql
                mysql --host $TEST_DB_HOST --port $TEST_DB_PORT -u $TEST_DB_USER -p$TEST_DB_PASSWORD -e 'SHOW DATABASES;'
                cd .. && mkdir wp && cd wp
                curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
                chmod +x wp-cli.phar
                sudo mv wp-cli.phar /usr/local/bin/wp
                wp core download
                wp config create --dbname=$TEST_DB_NAME --dbhost=$TEST_DB_HOST:$TEST_DB_PORT --dbuser=$TEST_DB_USER --dbpass=$TEST_DB_PASSWORD
                wp core install --url=$TEST_SITE_WP_URL --title=Test --admin_user=$TEST_SITE_ADMIN_USERNAME --admin_password=$TEST_SITE_ADMIN_PASSWORD --admin_email=$TEST_SITE_ADMIN_EMAIL
                yes | cp .env.actions.testing .env.testing
              env:
                WP_ROOT_FOLDER: "/var/www/html"
                TEST_SITE_WP_ADMIN_PATH: "/wp-admin"
                TEST_SITE_DB_NAME: ${{ job.services.mysql.env.MYSQL_DATABASE }}
                TEST_SITE_DB_HOST: "127.0.0.1"
                TEST_SITE_DB_USER: "admin"
                TEST_SITE_DB_PASSWORD: "password"
                TEST_SITE_DB_PORT: "3306"
                TEST_SITE_TABLE_PREFIX: "wp_"
                TEST_TABLE_PREFIX: "wp_"
                TEST_SITE_WP_URL: "http://wordpress.test"
                TEST_SITE_WP_DOMAIN: "wordpress.test"
                TEST_SITE_ADMIN_EMAIL: "admin@local.test"
                TEST_SITE_ADMIN_USERNAME: "admin"
                TEST_SITE_ADMIN_PASSWORD: "password"
                TEST_DB_NAME: ${{ job.services.mysql.env.MYSQL_DATABASE }}
                TEST_DB_HOST: "127.0.0.1"
                TEST_DB_USER: "admin"
                TEST_DB_PASSWORD: "password"
                TEST_DB_PORT: "3306"

            - name: Run integration tests
              run: composer test:integration
