name: Continuous integration checks

on:
    pull_request:
        branches: [master, develop]
    push:
        branches: [master]

jobs:
    phpcs_check:
        name: PHPCS check on PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4]

        steps:
            # Checkout repository
            - name: Checkout
              uses: actions/checkout@v2

            # Setup PHP versions, run checks
            - name: PHP setup
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                coverage: pcov

            - name: Get composer cache directory
              id: composer-cache
              run: |
                echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-composer-

            - name: Install composer packages
              run: composer install --no-progress

            - name: Check coding standards using PHPCS
              run: composer standards:check -- --runtime-set testVersion ${{ matrix.php }}-

    phpstan:
        name: PHPStan check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: PHP setup
              uses: shivammathur/setup-php@v2
              with:
                php-version: 7.2
                coverage: pcov

            - name: Get composer cache directory
              id: composer-cache
              run: |
                echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-composer-

            - name: Install composer packages
              run: composer install --no-progress

            - name: Analyse code using phpstan
              run: composer analyze

    tests:
        name: Integration tests
        runs-on: ubuntu-latest

        container:
            image: wordpress:5.4.1-php7.2
            env:
                WORDPRESS_DB_HOST: mysql
                WORDPRESS_DB_USER: admin
                WORDPRESS_DB_PASSWORD: ""
                WORDPRESS_DB_NAME: wordpresstest
            ports:
                - 8080:80
            volumes:
                - /__w/woo-solo-api/woo-solo-api:/var/www/html/wp-content/plugins/:rw
            options: --cpus 2

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: wordpresstest
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: exec into the container
              run: docker exec -it ${{ job.tests.container.name }} bash && ls


